"""Convert a continuous planner checkpoint to an Orca G-code inspection file.

This preserves per-layer routes. It does not plan printable layer transitions
or implement constant physical filament feed. No printer is contacted.
"""

import argparse
import json
import math
from pathlib import Path
import tempfile


def write_preview(data, settings, output, origin=(100., 100.)):
    height = float(settings['layer_height'])
    diameter = float(settings['filament_diameter'])
    rate = float(settings['filament_speed'])
    if not all(math.isfinite(x) and x > 0. for x in (height, diameter, rate)):
        raise ValueError('Layer height, filament diameter and feed must be positive and finite')
    if not all(math.isfinite(x) for x in origin):
        raise ValueError('Preview origin must be finite')
    filament_area = math.pi * (diameter * .5)**2
    stats = {'layers': 0, 'extrusion_moves': 0, 'travel_moves': 0,
             'invalid_layers': [], 'unresolved_paths': 0,
             'nominal_filament_mm': 0.}
    config = data.get('gcode_config')
    if config:
        output.write('; generated by OrcaSlicer continuous-extrusion inspector\n')
    output.write('; Continuous extrusion inspection ONLY. Not a printable program.\n'
                 '; Layer transitions are travels. Constant physical feed is not implemented by this file.\n'
                 '; Speeds and flow are nominal requests, not a Klipper motion simulation.\n'
                 '; No homing, heating, or printer start/end commands are included.\n'
                 'G21\nG90\nM83\nG92 E0\n')
    if config:
        config = dict(config, layer_height=str(height), initial_layer_print_height=str(height),
            filament_diameter=str(diameter), nozzle_diameter=str(settings.get('nozzle_diameter', .4)),
            gcode_flavor='klipper', printer_model='Continuous extrusion inspection',
            filament_map='1', filament_colour='#4FB6D4', filament_type='TPU',
            nozzle_type='undefine', nozzle_volume='0', physical_extruder_map='0')
        output.write('; CONFIG_BLOCK_START\n')
        for key, value in config.items():
            if '\n' in key or '\r' in key:
                raise ValueError('Invalid configuration key')
            value = str(value).replace('\n', '\\n').replace('\r', '\\r')
            output.write(f'; {key} = {value}\n')
        output.write('; CONFIG_BLOCK_END\n')
    previous = None
    previous_z = None
    for index, layer in enumerate(data['layers']):
        z = float(layer['z']) + height * .5
        if not math.isfinite(z) or (previous_z is not None and z <= previous_z):
            raise ValueError('Layer heights must be finite and increasing')
        previous_z = z
        stats['layers'] += 1
        if not all(layer.get(k, False) for k in ('connected', 'widths_valid', 'contained')):
            stats['invalid_layers'].append(index + 1)
        # Orca selects one tag dialect using the active printer profile. Emit
        # both so opening a checkpoint works with Klipper and Bambu profiles.
        output.write(f'; CHANGE_LAYER\n;LAYER_CHANGE\n; Z_HEIGHT: {z:.6f}\n;Z:{z:.6f}\n'
                     f'; LAYER_HEIGHT: {height:.6f}\n;HEIGHT:{height:.6f}\n')
        reason = str(layer.get('reason', '')).replace('\r', ' ').replace('\n', ' ')
        output.write(f'; Planner layer {index + 1}: {reason}\n')
        for unresolved, paths in ((False, layer['paths']), (True, layer.get('unresolved', []))):
            for path in paths:
                width = float(path['width'])
                points = [(float(p[0]) + origin[0], float(p[1]) + origin[1]) for p in path['points']]
                if len(points) < 2 or not all(math.isfinite(v) for p in points for v in p):
                    raise ValueError('Preview paths need at least two finite points')
                area = float(path.get('mm3_per_mm', height * (width - height * (1. - math.pi / 4.))))
                if not math.isfinite(width) or width < height or not math.isfinite(area) or area <= 0.:
                    raise ValueError('Invalid bead width or extrusion area')
                speed = rate * filament_area / area
                role = 'Gap infill' if unresolved else path.get('role', 'Internal solid infill')
                # Roles are comments, and must not inject executable lines.
                role = str(role).replace('\r', ' ').replace('\n', ' ')
                output.write(f'; FEATURE: {role}\n;TYPE:{role}\n; LINE_WIDTH: {width:.6f}\n;WIDTH:{width:.6f}\n')
                if unresolved:
                    stats['unresolved_paths'] += 1
                    output.write('; Unresolved route fragment, shown as gap infill for inspection\n')
                first = (*points[0], z)
                if previous != first:
                    # A separate Z move makes unfinished transitions visible
                    # without drawing a diagonal across the model.
                    output.write('G90\n')
                    if previous is None or previous[2] != z:
                        output.write(f'G0 Z{z:.6f} F600\n')
                        stats['travel_moves'] += 1
                    output.write(f'G0 X{first[0]:.6f} Y{first[1]:.6f} F6000\n')
                    stats['travel_moves'] += 1
                    output.write('G91\n')
                for a, b in zip(points, points[1:]):
                    distance = math.dist(a, b)
                    if distance == 0.:
                        continue
                    extrusion = distance * area / filament_area
                    # Orca reads individual axis words as floats. Relative XY
                    # retains short-segment precision without shrinking the
                    # model or distorting its nominal flow preview.
                    output.write(f'G1 X{b[0]-a[0]:.9f} Y{b[1]-a[1]:.9f} E{extrusion:.12f} F{60.*speed:.6f}\n')
                    stats['extrusion_moves'] += 1
                    stats['nominal_filament_mm'] += extrusion
                previous = (*points[-1], z)
    output.write('G90\n; End of inspection. Do not print this file.\n')
    return stats


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('checkpoint', type=Path)
    parser.add_argument('output', type=Path)
    parser.add_argument('--settings', type=Path, help='Required for older checkpoints without embedded settings')
    parser.add_argument('--config', type=Path, help='Orca config from inspector --preview-config, for older checkpoints')
    placement = parser.add_mutually_exclusive_group()
    placement.add_argument('--origin', type=float, nargs=2, metavar=('X', 'Y'), help='Explicit XY translation')
    placement.add_argument('--center', type=float, nargs=2, default=(100., 100.), metavar=('X', 'Y'), help='Center the part here; default 100 100')
    args = parser.parse_args()
    if args.checkpoint.resolve() == args.output.resolve():
        parser.error('Output must not replace the planner checkpoint')
    data = json.loads(args.checkpoint.read_text(encoding='utf-8'))
    if args.config:
        data['gcode_config'] = json.loads(args.config.read_text(encoding='utf-8-sig'))
    if not data.get('gcode_config'):
        parser.error('Checkpoint lacks Orca preview metadata; provide --config from inspector --preview-config')
    settings = json.loads(args.settings.read_text(encoding='utf-8')) if args.settings else data.get('settings')
    if settings is None:
        parser.error('This checkpoint requires --settings with the settings used to generate it')
    origin = args.origin
    if origin is None:
        points = [p for layer in data['layers'] for polygon in layer['region'] for ring in polygon for p in ring]
        if not points:
            parser.error('Checkpoint has no material regions')
        origin = tuple(args.center[i] - (min(p[i] for p in points) + max(p[i] for p in points)) * .5 for i in range(2))
    if args.origin is None:
        bed_x, bed_y = (2. * x for x in args.center)
        data['gcode_config']['printable_area'] = f'0x0,{bed_x}x0,{bed_x}x{bed_y},0x{bed_y}'
    # Publish only complete output. Invalid input cannot leave a partial .gcode.
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n',
                dir=args.output.parent, prefix=args.output.name + '.', suffix='.tmp', delete=False) as output:
            temporary = Path(output.name)
            stats = write_preview(data, settings, output, origin)
        temporary.replace(args.output)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    print(json.dumps(stats, indent=2))


if __name__ == '__main__':
    main()
